Development
wri/carbon-budget pull request #51
Opened 2024-02-06 18:48 UTC by melrose-wri

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [ x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [ x] Check the commit's or even all commits' message styles matches our requested structure.
- [ x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ x] Bugfix
- [ x] Feature
- [ x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

- Used SDPTv1
- Used older version of IPCC Tier 1 removal factors for temperate forests
- Lacked functionality to download and process tiles with no file pattern from gfw-data-lake
- Did not have an automated way to calculate ArcGIS zonal stats for model output

## What is the new behavior?

- Updated to use SDPTv2
- Added section to mp_prep_other_inputs_one_off.py to process 6 updated SDPTv2 tile datasets found on gfw-data-lake
- Modifed s3_file_download function for gfw-data-laketile sets
- Modified s3_folder_download function for gfw-data-lake tile sets
- Modified rewindow and mp_warp_to_hansen functions for gfw-data-lake tile sets
- Updated gain_spreadsheet with updated IPCC Tier 1 removal factors for temperate forests (20230821)
- Recreated soil c and soil c uncertainty tiles
- Added CarbonFluxQA code in analyses folder to calculate ArcGIS zonal stats for model output

## Does this introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information

2024-02-06 20:46 UTC, dagibbs22 requested changes
Just seems to be missing the QA script in the CarbonFluxQA folder.

2024-02-06 20:46 UTC, dagibbs22 commented on analyses/CarbonFluxQA
@melrose-wri There's nothing in the CarbonFluxQA folder. Should your Arc zonal stats script be in there? If it's somewhere else, the can you delete this folder, please?

2024-02-06 23:20 UTC, melrose-wri commented on analyses/CarbonFluxQA
The QA scripts were in that folder locally on my end, but I didn't realize they weren't being pushed because of the hidden .git file (copied over from the CarbonFluxQA repo). I removed the .git file and added this folder as a submodule in the carbon-budget repo so the files in the folder have now successfully pushed to the remote branch.

2024-02-07 14:22 UTC, dagibbs22 approved these changes

2024-02-07 14:23 UTC, merged